"""empty message

Revision ID: 15e7e31fa119
Revises: 4573208a16e3
Create Date: 2023-11-01 23:17:43.006702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e7e31fa119'
down_revision = '4573208a16e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('datatype', sa.String(length=25), nullable=False),
    sa.Column('text', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contact_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=75), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('datatype', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=400), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_requests_pkey')
    )
    op.drop_table('contact requests')
    # ### end Alembic commands ###
