"""empty message

Revision ID: 54a56bac28c3
Revises: 0b783d290806
Create Date: 2023-10-27 21:19:00.997493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a56bac28c3'
down_revision = '0b783d290806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('datatype', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_requests')
    # ### end Alembic commands ###
