"""empty message

Revision ID: a3932fae707a
Revises: 54a56bac28c3
Create Date: 2023-10-27 22:17:54.753555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3932fae707a'
down_revision = '54a56bac28c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.alter_column('datatype',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.alter_column('datatype',
               existing_type=sa.String(length=25),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
